### PR TITLE
chore(cmake): Pull changes

### PR DESCRIPTION
**Pull request by DerekMaggio**
Pull changes from https://github.com/Opentrons/cmake-utils/pull/14

### CODE REVIEW

**Review by sotaoverride — APPROVED** [review]
think i finally get the issue of clang vs ${Clang_EXECUTABLE}.

**Review by Laura-Danielle — APPROVED** [review]
lgtm

**Comment by DerekMaggio** [comment]
@Laura-Danielle I based this off the `can-simulator-vcan` branch as requested

**Comment by DerekMaggio** [comment]
Can someone make sure that running `cmake --preset host-gcc10` on a Mac still works?

**Comment by Laura-Danielle** [comment]
> Can someone make sure that running `cmake --preset host-gcc10` on a Mac still works?

I'll double check right now :)

**Comment by DerekMaggio** [comment]
Thanks!

**Comment by DerekMaggio** [comment]
Updated with fixes from [can-simulator-vcan](https://github.com/Opentrons/ot3-firmware/pull/67) and targeted to merge into `main`

**Pull request closed without merging**
