### PR TITLE
refactor(all): use the external oscillator for the system clock

### PR DESCRIPTION
**Pull request by Laura-Danielle**
Since the external oscilator is the same frequency as the internal oscilator, we should be able to use the same clock divisors.

### CODE REVIEW

**Review by fsinapi — COMMENTED** [review]
I think you also have to change the value in `stm32g4xx_hal_conf.h` for each target

**Review by sfoster1 — CHANGES_REQUESTED** [review]
- do this for the bootloaders (also a change in `system_stm32g4xx.c` for the bootloaders)
- for now, explicitly set `RCC_OscInitStruct.HSIState = RCC_HSI_OFF;` since the bootloader will have it enabled until we update the bootloaders on those boards
- agreed about the `hal_conf` change

**Review by sfoster1 — APPROVED** [review]
Looks good to me!

**Comment by ryanthecoder** [comment]
Tested on hardware and works well

**Pull request merged**
