### PR TITLE
feat(rear-panel): add the revb2 in anticipation of the new boards

### PR DESCRIPTION
**Pull request by ryanthecoder**
Adds the new revision which enables:
heartbeat LED
PGOOD input pin

### CODE REVIEW

**Comment by ryanthecoder** [comment]
Marked as draft until boards come in to test

**Review by sfoster1 — CHANGES_REQUESTED** [review]
Looks OK overall and I'm glad to get ahead but for the heartbeat LED to be useful it can't be timer driven, because then even if the actual processing the CPU does isn't working the timer will still be doing. We should toggle it either in the idle task or in a dedicated low priority freertos task so that we can use its flickering as an indication that the device is working properly.

**Review by sfoster1 — APPROVED** [review]
Looks good! Do we need to set the rev in the bootloader too?

**Comment by ryanthecoder** [comment]
There is no version in this bootloader, we us DNF for flashing and the "bootloader" just does the backup image copy and jumps to the application.

**Pull request merged**
