### PR TITLE
chore: enable werror on all firmware targets

### PR DESCRIPTION
**Pull request by sfoster1**
```
              _,-'|
           ,-'._  |
 .||,      |####\ |
\.`',/     \####| |
= ,. =      |###| | i cast -Werror
/ || \    ,-'\#/,'`.
  ||     ,'   `,,. `.
  ,|____,' , ,;' \| |
 (3|\    _/|/'   _| |
  ||/,-''  | >-'' _,\\
  ||'      ==\ ,-'  ,'
  ||       |  V \ ,|
  ||       |    |` |
  ||       |    |   \
  ||       |    \    \
  ||       |     |    \
  ||       |      \_,-'
  ||       |___,,--")_\
  ||         |_|   ccc/
  ||        ccc/
  ||                hjm
```
You have been visited by the -Werror -Wizard, who has fixed all the compiler warnings and enabled `-Werror` so that they are now compiler errors instead. No more shall we tolerate these warnings! Remove them with extreme prejudice.

### CODE REVIEW

**Comment by ahiuchingau** [comment]
Alt Text

**Review by sotaoverride — COMMENTED** [review]
Nice!

**Review by sotaoverride — APPROVED** [review]
LGTM!

**Review by Laura-Danielle — APPROVED** [review]
Looks good except can we just put the `motor_hardware.h` in the top level include rather than in each specific directory?

**Comment by sfoster1** [comment]
> Looks good except can we just put the `motor_hardware.h` in the top level include rather than in each specific directory?

no its project specific. some projects need one spi, some need 2, etc

**Comment by sfoster1** [comment]
_,-'|
           ,-'._  |
 .||,      |####\ |
\.`',/     \####| |
= ,. =      |###| | i cast -Werror
/ || \    ,-'\#/,'`.
  ||     ,'   `,,. `.
  ,|____,' , ,;' \| |
 (3|\    _/|/'   _| |
  ||/,-''  | >-'' _,\\
  ||'      ==\ ,-'  ,'
  ||       |  V \ ,|
  ||       |    |` |
  ||       |    |   \
  ||       |    \    \
  ||       |     |    \
  ||       |      \_,-'
  ||       |___,,--")_\
  ||         |_|   ccc/
  ||        ccc/
  ||                hjm

You have been visited by the -Werror -Wizard, who has fixed all the compiler warnings and enabled -Werror so that they are now compiler errors instead. No more shall we tolerate these warnings! Remove them with extreme prejudice.

**Pull request merged**
